### ISSUE TITLE
themes for jenny?

### ISSUE THREAD

**Issue by Avizini** [hmngwy/jenny#27]
something like this in .blogrc which user can configure and then jenny will build it according to what user has set.

`THEME="default"`
`# THEME="dark"`

also linking external css would be better because then jenny can have many themes without messing the code too much.

something like this in index.sh & post.sh

```
if theme=dark
 link dark css
else if theme=theme1
 link theme1 css
else
 link default css

```

**Comment by Avizini** [comment]
I've created one theme for jenny that doesn't mess with classes, just style needs to be replaced and everything works.

![jenny theme example](https://my.mixtape.moe/czknra.png)

**Comment by hmngwy** [comment]
Hello,

Your suggestions are clever, however the included theme is just to get people started, its CSS is inline because it's fast and simple, you can modify jenny's theme to suit your preferences by [supplying your own files](https://github.com/hmngwy/jenny#customization).

I am closing this with the `wontfix` label because this request/issue is more personal preference than anything, it can be done by the supplied customization "API", and is outside the general concern of the project.
